/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppBestbuybenchRouteImport } from './routes/_app.bestbuybench'
import { Route as AppModelsIndexRouteImport } from './routes/_app.models.index'
import { Route as ApiAgentTurnRouteImport } from './routes/api.agent.turn'
import { Route as AppProductSkuRouteImport } from './routes/_app.product.$sku'
import { Route as AppModelsGuideRouteImport } from './routes/_app.models.guide'
import { Route as AppModelsSplatRouteImport } from './routes/_app.models.$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppBestbuybenchRoute = AppBestbuybenchRouteImport.update({
  id: '/bestbuybench',
  path: '/bestbuybench',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent/turn',
  path: '/api/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductSkuRoute = AppProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsGuideRoute = AppModelsGuideRouteImport.update({
  id: '/models/guide',
  path: '/models/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsSplatRoute = AppModelsSplatRouteImport.update({
  id: '/models/$',
  path: '/models/$',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bestbuybench': typeof AppBestbuybenchRoute
  '/cart': typeof AppCartRoute
  '/chat': typeof AppChatRoute
  '/compare': typeof AppCompareRoute
  '/privacy': typeof AppPrivacyRoute
  '/scan': typeof AppScanRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/models/$': typeof AppModelsSplatRoute
  '/models/guide': typeof AppModelsGuideRoute
  '/product/$sku': typeof AppProductSkuRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/models/': typeof AppModelsIndexRoute
}
export interface FileRoutesByTo {
  '/bestbuybench': typeof AppBestbuybenchRoute
  '/cart': typeof AppCartRoute
  '/chat': typeof AppChatRoute
  '/compare': typeof AppCompareRoute
  '/privacy': typeof AppPrivacyRoute
  '/scan': typeof AppScanRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/models/$': typeof AppModelsSplatRoute
  '/models/guide': typeof AppModelsGuideRoute
  '/product/$sku': typeof AppProductSkuRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/models': typeof AppModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/bestbuybench': typeof AppBestbuybenchRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/models/$': typeof AppModelsSplatRoute
  '/_app/models/guide': typeof AppModelsGuideRoute
  '/_app/product/$sku': typeof AppProductSkuRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/_app/models/': typeof AppModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestbuybench'
    | '/cart'
    | '/chat'
    | '/compare'
    | '/privacy'
    | '/scan'
    | '/search'
    | '/settings'
    | '/models/$'
    | '/models/guide'
    | '/product/$sku'
    | '/api/agent/turn'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bestbuybench'
    | '/cart'
    | '/chat'
    | '/compare'
    | '/privacy'
    | '/scan'
    | '/search'
    | '/settings'
    | '/'
    | '/models/$'
    | '/models/guide'
    | '/product/$sku'
    | '/api/agent/turn'
    | '/models'
  id:
    | '__root__'
    | '/_app'
    | '/_app/bestbuybench'
    | '/_app/cart'
    | '/_app/chat'
    | '/_app/compare'
    | '/_app/privacy'
    | '/_app/scan'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/'
    | '/_app/models/$'
    | '/_app/models/guide'
    | '/_app/product/$sku'
    | '/api/agent/turn'
    | '/_app/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bestbuybench': {
      id: '/_app/bestbuybench'
      path: '/bestbuybench'
      fullPath: '/bestbuybench'
      preLoaderRoute: typeof AppBestbuybenchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models/': {
      id: '/_app/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agent/turn': {
      id: '/api/agent/turn'
      path: '/api/agent/turn'
      fullPath: '/api/agent/turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/product/$sku': {
      id: '/_app/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof AppProductSkuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models/guide': {
      id: '/_app/models/guide'
      path: '/models/guide'
      fullPath: '/models/guide'
      preLoaderRoute: typeof AppModelsGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models/$': {
      id: '/_app/models/$'
      path: '/models/$'
      fullPath: '/models/$'
      preLoaderRoute: typeof AppModelsSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBestbuybenchRoute: typeof AppBestbuybenchRoute
  AppCartRoute: typeof AppCartRoute
  AppChatRoute: typeof AppChatRoute
  AppCompareRoute: typeof AppCompareRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppScanRoute: typeof AppScanRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppModelsSplatRoute: typeof AppModelsSplatRoute
  AppModelsGuideRoute: typeof AppModelsGuideRoute
  AppProductSkuRoute: typeof AppProductSkuRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBestbuybenchRoute: AppBestbuybenchRoute,
  AppCartRoute: AppCartRoute,
  AppChatRoute: AppChatRoute,
  AppCompareRoute: AppCompareRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppScanRoute: AppScanRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppModelsSplatRoute: AppModelsSplatRoute,
  AppModelsGuideRoute: AppModelsGuideRoute,
  AppProductSkuRoute: AppProductSkuRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
